### ISSUE TITLE
Problem with pushes from python to android phone

### ISSUE THREAD

**Issue by marksev1** [guglielmino/pushetta-py#5]
Not sure where to ask you but here it goes. For pushes from Pushetta to arrive to mobile phone I need to turn it off and then on again, do you maybe know what is the problem? Since on the Pushetta website they get  immediately shown but they don't get pushed to the mobile phone until I reboot it...

So after reboot it works like a champ, I get the old pushes...but before it doesn't...maybe this is also because I pushed from two different computers?)?

**Comment by guglielmino** [comment]
I can't remember other users affected by the problem you are describing. Normally isn't necessary to turn off and on again the device to receive pushes. It might be a problem on you specific device, can you try with another one?

**Comment by marksev1** [comment]
Nope don't have another...its a Nexus 5 running android 5.1.1...Its wierd pushes get registered on your website but don't get delivered to the phone until reboot...weird... (now currently it works, gonna retry tomorrow in the evening and see if it still works), if its a problem of using multiple computers with different ip's and the same api key.

Now I figured something new out...If I turn off and on data I also get the pushes.

**Comment by marksev1** [comment]
Can you give me more feedback, anything else I can do?

**Comment by guglielmino** [comment]
It might be a problem with Your OS, have You checked if there are updates
for Your android version?

On 15 marzo 2017 a 09:05:46, marksev1 (notifications@github.com) scritto:

Can you give me more feedback, anything else I can do?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/guglielmino/pushetta-py/issues/5#issuecomment-286668485>,
or mute the thread

**Comment by marksev1** [comment]
This shouldn't be a problem, with pushbullet and other apps I got notifications immediatly...Now i've set your app as "priority" for notification, gonna see if that helps.

**Comment by guglielmino** [comment]
Ok, let me know.

On 15 marzo 2017 a 09:54:49, marksev1 (notifications@github.com) scritto:

This shouldn't be a problem, with pushbullet and other apps I got
notifications immediatly...Now i've set your app as "priority" for
notification, gonna see if that helps.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/guglielmino/pushetta-py/issues/5#issuecomment-286678428>,
or mute the thread

**Comment by marksev1** [comment]
Now that they are set to priority it seems to work...Tested just one time, will see in the next few days if it will be reliable. Otherwise Pushetta is really cool! Thanks!
