### ISSUE TITLE
Import Pushetta not working

### ISSUE THREAD

**Issue by Newtt** [guglielmino/pushetta-py#6]
Hi there, 

When I try to import like this : 

from pushetta import Pushetta

I got the following error : 

ImportError: cannot import name Pushetta.

Do you have any clue if it's "me" related ?

**Comment by guglielmino** [comment]
Hello,

did you call your script pushetta.py? If this is the case change his name
and try again.


On 21 giugno 2017 a 08:42:15, Matt (notifications@github.com) scritto:

Hi there,

When I try to import like this :

from pushetta import Pushetta

I got the following error :

ImportError: cannot import name Pushetta.

Do you have any clue if it's "me" related ?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/guglielmino/pushetta-py/issues/6>, or mute the thread

**Comment by Newtt** [comment]
Omg I'm so dumb it's surely that ;) thanks for your help, I'll try to change the name and try again.

1000 thanks ;)

**Comment by Newtt** [comment]
Hum, I am effectively dumb :) that was the problem thank you. :1st_place_medal:
